### ISSUE TITLE
How to train the model?

### ISSUE THREAD

**Issue by zhw2020913** [rpm1412/LUS_Video_Summarization#1]
Can you please tell me how to train the model onmy own dataset ?

**Comment by rpm1412** [comment]
Hello,
Please find the references to open source repositories for deep reinforcement learning for unsupervised video summarization cited in the manuscript :
1) https://github.com/KaiyangZhou/pytorch-vsumm-reinforce
2) https://github.com/Lorna-Liu/ultrasound_vsumm_RL

Thanks !

**Comment by zhw2020913** [comment]
ok，thanks.
